spring:
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:complex_password}

  datasource:
    url: jdbc:log4jdbc:mysql://3.35.147.68:3306/SWYP6?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: swyp6
    password: Swyp10_6group
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 300
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

file:
  upload:
    path: /app/uploads/
    max-size: 52428800
    max-request-size: 104857600
    allowed-extensions: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,txt

server:
  port: 8080

logging:
  level:
    root: WARN
    com.backend: INFO
    org.springframework: WARN