spring:
  application:
    name: PackUp-Backend

  profiles:
    active: local

  security:
    user:
      name: admin
      password: 1234

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    static-path-pattern: /static/**
  
  web:
    resources:
      static-locations:
      - classpath:/static/

  # 데이터소스 설정
  datasource:
    url: jdbc:log4jdbc:mysql://3.35.147.68:3306/SWYP6?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: swyp6
    password: Swyp10_6group
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
        maximum-pool-size: 300
        minimum-idle: 10
        idle-timeout: 600000
        max-lifetime: 1800000
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # create, create-drop, validate, update, none
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml

logging:
  config: classpath:logback-spring.xml

server:
  port: 80