spring:
  application:
    name: PackUp-Backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
  
  web:
    resources:
      static-locations:
      - classpath:/static/
      - file:${file.upload.path}
  
  servlet:
    multipart:
      max-file-size: ${file.upload.max-size}
      max-request-size: ${file.upload.max-request-size}
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml

logging:
  config: classpath:logback-spring.xml